### ISSUE TITLE
Support testing reverse dependencies 

### ISSUE THREAD

**Issue by thesamesam** [slashbeast/pkg-testing-tools#1]
Tatt generates two scripts:
- USE flag combination tester
- Reverse dependency (rdeps) tester, i.e. checks if packages which depend on the thing we're stabilising still build with the new version.

This could replace tatt entirely for me if the rdeps feature could be emulated to some degree.

Issues with tatt:
I think tatt may use eix to parse the lists from https://qa-reports.gentoo.org/output/genrdeps/rindex/ but ends up calling out to eix with duplicate atoms. 

When running tatt -b 699328 (a qtwebengine bug), it took several hours to compile the list of rdeps needed, even though it would later only cut down to a sample of 10.

**Comment by juippis** [comment]
I use https://github.com/juippis/my-gentoo-lxd-scripts/blob/master/container/bin/rdeptester.sh with pkg-testing-tools, although, it might generate "duplicate" atoms if you consider cases like these duplicates:
```
x11-wm/enlightenment-0.24.2-r1:wayland
x11-wm/enlightenment-0.24.2-r1:xwayland
x11-wm/enlightenment-0.24.2-r1:connman
```
Would definitely want to get this built-in to pkg-testing-tool.

**Comment by slashbeast** [comment]
Project now being archived and turned into read-only, no further development will happen in this repository.
