### ISSUE TITLE
0.1.1 is installed as 0.1.0

### ISSUE THREAD

**Issue by mgorny** [slashbeast/pkg-testing-tools#15]
You seem to have forgotten to update `version`:

```
 *  FILES:+usr/lib/python3.9/site-packages/pkg_testing_tools-0.1.0.dist-info/METADATA
```

(from 0.1.1)

**Comment by slashbeast** [comment]
You are right, thanks for pointing it out. Will bump to 0.1.2 to not recreate tags.
