### ISSUE TITLE
Support prefixes for report names

### ISSUE THREAD

**Issue by thesamesam** [slashbeast/pkg-testing-tools#2]
Allow specifying a prefix for all report names / a template for their names, so there's no need to set it on each invocation.

Alternatively, default to a name including the atom (just the first if multiple), and allow specifying a directory to dump them into.

**Comment by slashbeast** [comment]
I think I will go with `--report-dir` for this, to keep `--report` as single joint file, so the directory can be automatically created if it does not exist.

**Comment by slashbeast** [comment]
Project now being archived and turned into read-only, no further development will happen in this repository.
