### ISSUE TITLE
Log test failures separately

### ISSUE THREAD

**Issue by thesamesam** [slashbeast/pkg-testing-tools#3]
It'd be great to be able to apply some filter like "FAIL:" to output and dump info (including the package and USE combo) to a file. 

Perhaps in this case the workdir should be saved elsewhere else for inspection, or just some of the surrounding lines can be pulled out and saved to a file for context.

A more abstract way of doing this would be allow configurable filters for this kind of behaviour rather than specifically searching for a string like "FAIL:".

**Comment by slashbeast** [comment]
Project now being archived and turned into read-only, no further development will happen in this repository.
