### ISSUE TITLE
different FEATURES per package but not globally (enable QA notifications only for what we're testing, not for every dep)

### ISSUE THREAD

**Issue by juippis** [slashbeast/pkg-testing-tools#4]
Hi, 
as discussed in IRC I'd love it if this tool was able to enable some QA notifications listed here, 
https://wiki.gentoo.org/wiki/Package_testing#make.conf
just for the package we're testing. It'd become too much noise if they were enabled for all the deps.

These are my testing settings currently:
```
CFLAGS="-march=native -O2 -pipe -frecord-gcc-switches"
CXXFLAGS="${CFLAGS}"
LDFLAGS="${LDFLAGS} -Wl,--defsym=__gentoo_check_ldflags__=0"

FEATURES="network-sandbox qa-unresolved-soname-deps split-log split-elog test"

PORTAGE_ELOG_CLASSES="log warn error qa"
PORTAGE_ELOG_SYSTEM="echo save"
```

**Comment by juippis** [comment]
Oh and also the different CFLAGS and LDFLAGS would be really important for the package we're testing, but good to be ignored for deps.

**Comment by slashbeast** [comment]
I've moved around FEATURES to be only enabled for tested atom, enabled qa soname symbols unconditionally and added --extra-env-file switch, can be used multiple times to specify more than one file.

**Comment by juippis** [comment]
Thanks, this has worked for me.
